name: Backend Deployment

on:
  push:
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Build Backend
        run: |
          cd backend
          npm run build

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: demowebapli
          slot-name: production
          publish-profile: ${{ secrets.WEB_APP_DEPLOY }}
          package : .